blank_issues_enabled: false
contact_links:
    - name: Projgen Issue Tracker
      url: https://github.com/projgen/core/issues
      about: For technical issues, bugs, and feature requests related to Projgen.
